import { Router, type Request, type Response } from 'express';
import type { PipelinePassId } from '@shared/types';
import { pipelineOrchestrator } from '../services/pipeline/orchestrator.js';

const router = Router();

/**
 * GET /api/v2/pipelines/:pipelineId/artifacts
 * Lists generated artifacts for a pipeline.
 */
router.get('/v2/pipelines/:pipelineId/artifacts', (req: Request, res: Response) => {
  const { pipelineId } = req.params;
  const list = pipelineOrchestrator.getArtifacts(pipelineId);
  if (!list) {
    return res.status(404).json({ success: false, error: `Pipeline not found: ${pipelineId}` });
  }

  return res.json(list);
});

/**
 * GET /api/v2/pipelines/:pipelineId/artifacts/:passId
 * Returns artifact payload generated by a specific pass.
 */
router.get('/v2/pipelines/:pipelineId/artifacts/:passId', (req: Request, res: Response) => {
  const { pipelineId, passId } = req.params;
  const artifact = pipelineOrchestrator.getArtifactByPass(pipelineId, passId as PipelinePassId);
  if (!artifact) {
    return res.status(404).json({
      success: false,
      error: `Artifact not found for pipeline ${pipelineId} and pass ${passId}`,
    });
  }

  return res.json(artifact);
});

export default router;
